### ISSUE TITLE
Compatibility issue with Rails 6.1 ?

### ISSUE THREAD

**Issue by mmagn** [unabridged/motion#71] opened 2020-12-31 16:17 UTC
Hi, first of all thank you for your work on Motion, your gem is really helpful and it is a pleasure to use it.

I am using the 0.4.4 version of the gem and everything is fine on Rails 6.0.3. 

I tried to upgrade to Rails 6.1, but now my components are no longer updated after an interaction and sometimes the component disappears from the page.

I have investigated few hours without success, there is no error message in the logs...

I was able to reproduce my problem on a cloned repository of motion-demos : https://github.com/mmagn/motion-demos/

Am I missing something?

Thanks for your help.

**Comment by latortuga** [comment] 2020-12-31 16:56
Thank you for the report and nice words! We have not yet tested with Rails 6.1 so that would explain why it doesn't work yet. We'll put it up on the priority list!

**Comment by EtienneDepaulis** [comment] 2021-01-12 06:46
Hello, we have the same issue as well : no more live update :/

**Comment by dannyvanhoof** [comment] 2021-01-12 16:02
Similarproblem: update leaves completely empty component...

**Comment by HashNotAdam** [comment] 2021-01-13 13:14
I've only had a very short amount of time to look at this but it seems like, when `render_in` is being called, the ActionView view has a layout of `nil` which is not allowed.

I'll try to take another look tomorrow but I don't actually know how it is expected to get a layout; if anyone has a hint on that, it would be valuable

**Comment by HashNotAdam** [comment] 2021-01-14 09:15
So far I've managed to work out that the difference is that now the whole page is being rendered instead of just the component which is confusing the DOM differ

**Comment by dannyvanhoof** [comment] 2021-01-27 09:00
All - I hesitate to write it - but I have the impression motion is not actively maintained? 6.1 is out since December - and the only gem blocking us from the new release is motion... Did we make the wrong choice to rely on motion in our product? When we made that choice, the functionality looked so attractive - and it still is - but without active maintenance it becomes a problem :-(

**Comment by HashNotAdam** [comment] 2021-01-27 20:36
> All - I hesitate to write it - but I have the impression motion is not actively maintained? 6.1 is out since December - and the only gem blocking us from the new release is motion... Did we make the wrong choice to rely on motion in our product? When we made that choice, the functionality looked so attractive - and it still is - but without active maintenance it becomes a problem :-(

Being an open-source product, you could always help with the maintenance. I've already done the hardest part of the work but require support getting it over the line.

**Comment by dannyvanhoof** [comment] 2021-01-29 08:59
I integrated your fork in our application, and ran the entire test suite in Rails 6.1. All tests completed succesfully - so we are eagerly waiting for you to officially release #73!

**Comment by latortuga** [comment] 2021-01-29 16:11
Thanks for the reports and contribution all, we'll hopefully be able to get this resolved in the near future!

**Comment by HashNotAdam** [comment] 2021-01-31 22:42
> Thanks for the reports and contribution all, we'll hopefully be able to get this resolved in the near future!

Thanks, @latortuga, I might be able to get more time to look at it this week but even if someone could job on the PR and explain how the test system works, that would save me a tonne of time finishing off the PR. Otherwise, I'll try to set a day aside to dig into it

**Comment by dannyvanhoof** [comment] 2021-02-10 11:00
@latortuga Any progress with testing/releasing the 6.1 changes?

**Comment by zog** [comment] 2021-03-02 07:46
Hey @HashNotAdam ,

I'm willing to help solving this issue, unfortunately I was unable to reproduce the failing specs on my local machine (matching ruby version etc.). Any pointer ?

**Comment by latortuga** [comment] 2021-03-11 19:53
Apologies for the lateness on this folks but we have pushed out a fix for Rails 6.1 today. Please upgrade to v0.5 and give it a try!

**Closed by latortuga** 2021-03-11 19:53 UTC
Labels: bug
